USE_AUTODISCOVER = True
CORE_URL = ["http://localhost:8001/", ]
INTERFACES = [
    {'iface':   'eth1',
     'cost':    100},
]
VXLAN_INTERFACE='eth1'
VXLAN_MULTICAST='239.0.0.1'
QUAGGA_PASSWORD = "_QUAGGA_PASSWORD"
OSPF_TOKEN = '_OSPF_TOKEN'
IFACE_NAME_LENGTH = 15
CREATE_CONFIG_BACKUPS = False
